apiVersion: batch/v1
kind: Job
metadata:
  generateName: ${USER}-job-train-${JOB_SUFFIX}
  labels:
    eidf/user: ${USER}
    kueue.x-k8s.io/queue-name: ${QUEUE_NAME}
    kueue.x-k8s.io/priority-class: batch-workload-priority
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  backoffLimit: 2147483647
  activeDeadlineSeconds: 864000
  template:
    metadata:
      labels:
        eidf/user: ${USER}
    spec:
      restartPolicy: OnFailure
      # Replace nodeSelector with affinity to allow multiple GPU types.
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-H200
      # Add tolerations to allow scheduling on nodes with specific taints.
      tolerations:
        - key: "eidf098"
          operator: "Equal"
          value: "True"
          effect: "NoSchedule"
        - key: "eidf107"
          operator: "Equal"
          value: "True"
          effect: "NoSchedule"
      containers:
        - name: stylegan-fingerprint
          image: kaiyaoed/my_app:latest  # Ensure CUDA version matches host drivers
          workingDir: "/nfs-user-107/authprint"
          env:
            - name: TORCH_NCCL_ASYNC_ERROR_HANDLING
              value: "1"
            - name: NCCL_DEBUG
              value: "INFO"
            - name: NCCL_IB_DISABLE
              value: "1"
            - name: MAX_DELTA
              value: "${MAX_DELTA}"
            - name: NCCL_IB_HCA
              value: "^mlx5"
            - name: PYTHONPATH
              value: "/nfs-user-107/authprint"
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Setting up environment..."
              mkdir -p /nfs-user-107/authprint/results
              mkdir -p /nfs-user-107/authprint/evaluation_results
              mkdir -p /nfs-user-107/authprint/pretrained_models
              
              # Check and download pretrained models if they don't exist
              if [ ! -f "/nfs-user-107/authprint/pretrained_models/vgg16-397923af.pth" ]; then
                echo "Downloading VGG16 weights..."
                curl -L -o /nfs-user-107/authprint/pretrained_models/vgg16-397923af.pth \
                  "https://download.pytorch.org/models/vgg16-397923af.pth"
              fi
              
              if [ ! -f "/nfs-user-107/authprint/pretrained_models/weights-inception-2015-12-05-6726825d.pth" ]; then
                echo "Downloading Inception weights..."
                curl -L -o /nfs-user-107/authprint/pretrained_models/weights-inception-2015-12-05-6726825d.pth \
                  "https://github.com/toshas/torch-fidelity/releases/download/v0.2.0/weights-inception-2015-12-05-6726825d.pth"
              fi
              
              # Create symlinks to the expected locations
              mkdir -p /root/.cache/torch/hub/checkpoints
              ln -sf /nfs-user-107/authprint/pretrained_models/vgg16-397923af.pth /root/.cache/torch/hub/checkpoints/
              ln -sf /nfs-user-107/authprint/pretrained_models/weights-inception-2015-12-05-6726825d.pth /root/.cache/torch/hub/checkpoints/
              
              # Download StyleGAN models if they don't exist
              if [ ! -f "/nfs-user-107/authprint/ffhq70k-paper256-ada.pkl" ]; then
                echo "Downloading StyleGAN FFHQ model..."
                curl -o /nfs-user-107/authprint/ffhq70k-paper256-ada.pkl \
                  "https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/paper-fig7c-training-set-sweeps/ffhq70k-paper256-ada.pkl"
              fi
              
              if [ ! -f "/nfs-user-107/authprint/lsuncat100k-paper256-ada.pkl" ]; then
                echo "Downloading StyleGAN LSUN Cat model..."
                curl -o /nfs-user-107/authprint/lsuncat100k-paper256-ada.pkl \
                  "https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/paper-fig7c-training-set-sweeps/lsuncat100k-paper256-ada.pkl"
              fi
              
              # Run training directly with torchrun
              echo "Starting training..."
              export PYTHONPATH=$PYTHONPATH:/nfs-user-107/authprint
              
              torchrun --nproc_per_node=2 \
                      --nnodes=1 \
                      --node_rank=0 \
                      --master_addr=127.0.0.1 \
                      --master_port=12345 \
                      scripts/train.py \
                      --model_type stable-diffusion \
                      --sd_model_name "stabilityai/stable-diffusion-2-1" \
                      --img_size 1024 \
                      --batch_size 32 \
                      --total_iterations 5000000 \
                      --checkpoint_interval 1000 \
                      --image_pixel_count 1024 \
                      --image_pixel_set_seed 42 \
                      --sd_num_inference_steps 25 \
                      --sd_guidance_scale 7.5 \
                      --sd_prompt 'a high quality image' \
                      --sd_decoder_size "L" \
                      --lr 1e-5 \
                      --sd_enable_cpu_offload \
                      --enable_multi_prompt \
                      --prompt_source "diffusiondb" \
                      --diffusiondb_subset "2m"
              
              exit_status=$?
              echo "Training finished with exit status $exit_status"
          resources:
            limits:
              nvidia.com/gpu: "2"
              cpu: "4"
              memory: "16Gi"
          volumeMounts:
            - name: nfs-user-107
              mountPath: /nfs-user-107
            - name: nfs-user-029
              mountPath: /nfs-user-029
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: nfs-user-107
          nfs:
            server: 10.24.6.77
            path: /user/s2470447-eidf107
        - name: nfs-user-029
          nfs:
            server: 10.24.1.255
            path: /user/s2470447-infk8s
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
